version: '3'

services:
  backend:
    build: ./docker/backend
    container_name: petstore-backend
    tty: true
    working_dir: /opt/petstore
    volumes:
      - .:/opt/petstore
    ports:
      - 8081:8080
    extra_hosts:
      - host.docker.internal:host-gateway
  frontend:
    build: ./docker/frontend
    container_name: petstore-frontend
    tty: true
    working_dir: /opt/petstore
    volumes:
      - .:/opt/petstore
    ports:
      - 1235:1234
    extra_hosts:
      - host.docker.internal:host-gateway
  nginx:
    build: ./docker/nginx
    container_name: petstore-nginx
    tty: true
    volumes:
      - ./docker/nginx/petstore.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    ports:
      - 80:80
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - backend
      - frontend
